spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://192.168.100.100:3000/mas01as?serverTimezone=Asia/Seoul
    username: user01
    password: user01