server:
  port: 8889
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/
  server:
#    waitTimeInMsWhenSyncEmpty: 5
    enableSelfPreservation: false